[package]
name = "stdlib"
version = "0.1.0"
edition = "2024"

[dependencies]
executor.workspace = true
geo.workspace = true
inventory.workspace = true
smallvec.workspace = true
stdlib-macros.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
latex.workspace = true
libtess2.workspace = true
