//! `Keyed`: field-wise interpolation, the base capability slot types need.
//!
//! Spec (`OPERATORS.md`): implemented for f64, Vec2/3/4, Color, tuples,
//! `Vec<T: Keyed>`, `Option<T: Keyed>`, `MeshValue`, and `Hold<T: PartialEq>`.
//! `MeshValue`'s impl (recursive structural lerp) lives in `mesh.rs` /
//! `lerp.rs` since it needs the retained-tree machinery; everything else is
//! here.

use crate::error::{Error, Result};

/// Field-wise interpolation.
pub trait Keyed: Clone + 'static {
    fn lerp(&self, other: &Self, t: f64) -> Result<Self>;
}

impl Keyed for f64 {
    fn lerp(&self, other: &Self, t: f64) -> Result<Self> {
        Ok(self + (other - self) * t)
    }
}

impl Keyed for f32 {
    fn lerp(&self, other: &Self, t: f64) -> Result<Self> {
        Ok(self + (other - self) * t as f32)
    }
}

/// Newtype wrapper for equality-only slots: `lerp` succeeds only when the two
/// values are equal (returning a clone), otherwise it errors. `#[hold]` on a
/// derive field applies this behavior transparently (see `rust_scene_macros`)
/// without requiring the field's declared type to actually be `Hold<T>`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub struct Hold<T>(pub T);

impl<T> Hold<T> {
    pub fn new(value: T) -> Self {
        Self(value)
    }

    pub fn into_inner(self) -> T {
        self.0
    }
}

impl<T: Clone + PartialEq + 'static> Keyed for Hold<T> {
    fn lerp(&self, other: &Self, _t: f64) -> Result<Self> {
        hold_lerp(&self.0, &other.0).map(Hold)
    }
}

/// Shared equality-only lerp used both by `Hold<T>` and by `#[hold]` fields
/// generated by the derive macros (which store the plain `T`, not `Hold<T>`).
pub fn hold_lerp<T: Clone + PartialEq>(a: &T, b: &T) -> Result<T> {
    if a == b {
        Ok(a.clone())
    } else {
        Err(Error::message("cannot lerp: held value differs"))
    }
}

impl<T: Keyed> Keyed for Option<T> {
    fn lerp(&self, other: &Self, t: f64) -> Result<Self> {
        match (self, other) {
            (None, None) => Ok(None),
            (Some(a), Some(b)) => Ok(Some(a.lerp(b, t)?)),
            _ => Err(Error::message(
                "cannot lerp optional values: one side is present and the other is absent",
            )),
        }
    }
}

impl<T: Keyed> Keyed for Vec<T> {
    fn lerp(&self, other: &Self, t: f64) -> Result<Self> {
        if self.len() != other.len() {
            return Err(Error::message(format!(
                "cannot lerp lists of different lengths: {} vs {}",
                self.len(),
                other.len()
            )));
        }
        self.iter().zip(other).map(|(a, b)| a.lerp(b, t)).collect()
    }
}

macro_rules! impl_keyed_tuple {
    ($($idx:tt $T:ident),+) => {
        impl<$($T: Keyed),+> Keyed for ($($T,)+) {
            fn lerp(&self, other: &Self, t: f64) -> Result<Self> {
                Ok(($(self.$idx.lerp(&other.$idx, t)?,)+))
            }
        }
    };
}

impl_keyed_tuple!(0 A);
impl_keyed_tuple!(0 A, 1 B);
impl_keyed_tuple!(0 A, 1 B, 2 C);
impl_keyed_tuple!(0 A, 1 B, 2 C, 3 D);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn f64_lerps_linearly() {
        assert_eq!(1.0.lerp(&3.0, 0.5).unwrap(), 2.0);
    }

    #[test]
    fn hold_requires_equality() {
        let a = Hold::new("a".to_string());
        let b = Hold::new("a".to_string());
        assert_eq!(a.lerp(&b, 0.3).unwrap(), a);

        let c = Hold::new("b".to_string());
        assert!(a.lerp(&c, 0.3).is_err());
    }

    #[test]
    fn option_requires_matching_variant() {
        assert_eq!(Some(1.0).lerp(&Some(3.0), 0.5).unwrap(), Some(2.0));
        assert!(None::<f64>.lerp(&Some(3.0), 0.5).is_err());
    }

    #[test]
    fn vec_requires_matching_length() {
        assert_eq!(
            vec![0.0, 10.0].lerp(&vec![2.0, 20.0], 0.5).unwrap(),
            vec![1.0, 15.0]
        );
        assert!(vec![0.0].lerp(&vec![1.0, 2.0], 0.5).is_err());
    }

    #[test]
    fn tuple_lerps_elementwise() {
        assert_eq!((0.0, 10.0).lerp(&(2.0, 20.0), 0.5).unwrap(), (1.0, 15.0));
    }
}
