//! The trait layer: `Keyed` lives in `keyed.rs`; this module holds the
//! operator/constructor body traits (`Apply`, `ApplyEndpoints`, `Construct`)
//! and the object-safe retained-node traits (`OperatorNode`, `ConstructorNode`)
//! that back `MeshValue`'s tree. Kept hand-implementable — this is both the
//! escape hatch for users who don't want the macros and the test surface for
//! this crate.

use std::any::{Any, TypeId};

use crate::{error::Result, mesh::MeshValue};

/// Identity for structural lerp rule 3 (same operator/constructor → lerp
/// slots) and rule 4 (operator popping). Derived from the `TypeId` of the
/// operator/constructor struct.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash)]
pub struct OpId(TypeId);

impl OpId {
    pub fn of<T: 'static>() -> Self {
        Self(TypeId::of::<T>())
    }
}

/// Type-erased view onto a single argument slot, used for `live!` field
/// wiring (milestone 5, not implemented yet). Deliberately decoupled from
/// `Keyed`: lerp behavior for a slot is decided by the concrete
/// `OperatorNode`/`ConstructorNode` impl (via `Keyed` or hold-equality), not
/// by `Slot` itself, which only needs to support type-erased get/set.
///
/// Blanket-implemented for every `Clone + 'static` type, so `#[hold]` fields
/// (which need not be `Keyed`) are just as addressable as ordinary slots.
pub trait Slot: Any {
    fn as_any(&self) -> &dyn Any;
    fn as_any_mut(&mut self) -> &mut dyn Any;
}

impl<T: Clone + 'static> Slot for T {
    fn as_any(&self) -> &dyn Any {
        self
    }

    fn as_any_mut(&mut self) -> &mut dyn Any {
        self
    }
}

/// The operator body: the common case. The identity endpoint defaults to the
/// untouched operand.
pub trait Apply: Clone + 'static {
    fn apply(&self, target: MeshValue) -> MeshValue;
}

/// The operator body for operators that need a custom identity endpoint
/// (MCL's explicit `[identity, modified]` return).
pub trait ApplyEndpoints: Clone + 'static {
    fn endpoints(&self, target: MeshValue) -> (MeshValue, MeshValue);
}

/// The constructor body: the leaf-node analog of `Apply`, minus the operand.
pub trait Construct: Clone + 'static {
    fn construct(&self) -> MeshValue;
}

/// What the retained tree stores for an applied operator. Object-safe,
/// generated by `#[derive(Operator)]` / `#[operator]`; hand-written only in
/// tests and for the `Shift` reference operator (`ops::shift`).
///
/// `as_any` is not part of the signature given in `OPERATORS.md`'s sketch but
/// is required to make `lerp_slots` implementable at all (downcasting
/// `other: &dyn OperatorNode` to the concrete operator type to read its
/// fields) — an object-safety necessity rather than an API change.
pub trait OperatorNode: 'static {
    fn op_id(&self) -> OpId;
    fn endpoints(&self, target: MeshValue) -> (MeshValue, MeshValue);
    fn lerp_slots(&self, other: &dyn OperatorNode, t: f64) -> Result<Box<dyn OperatorNode>>;
    fn slot(&self, index: usize) -> &dyn Slot;
    fn slot_mut(&mut self, index: usize) -> &mut dyn Slot;
    fn slot_count(&self) -> usize;
    fn clone_node(&self) -> Box<dyn OperatorNode>;
    fn debug_name(&self) -> &'static str;
    fn as_any(&self) -> &dyn Any;
}

/// The leaf-node analog of `OperatorNode`: same slots, same rule-3 identity
/// matching, `evaluate` in place of `endpoints` (constructors have no operand
/// to pop through, so there is no rule-4 analog for them).
pub trait ConstructorNode: 'static {
    fn op_id(&self) -> OpId;
    fn evaluate(&self) -> MeshValue;
    fn lerp_slots(&self, other: &dyn ConstructorNode, t: f64) -> Result<Box<dyn ConstructorNode>>;
    fn slot(&self, index: usize) -> &dyn Slot;
    fn slot_mut(&mut self, index: usize) -> &mut dyn Slot;
    fn slot_count(&self) -> usize;
    fn clone_node(&self) -> Box<dyn ConstructorNode>;
    fn debug_name(&self) -> &'static str;
    fn as_any(&self) -> &dyn Any;
}

/// Any type that can be pushed onto a `MeshValue` as an operator layer via
/// `MeshValue::with`.
pub trait OperatorStruct: OperatorNode + Clone + 'static {}
impl<T: OperatorNode + Clone + 'static> OperatorStruct for T {}
