// might need to add lambdas, labels
#[derive(Default, Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum Token {
    #[default]
    Illegal,

    Newline,
    Whitespace,

    Comment,

    StatefulReference,
    Plus,
    Minus,
    Multiply,
    Power,
    Divide,
    IntegerDivide,
    KeyValueMap,
    Assign,
    DotAssign,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    And,
    Not,
    Or,
    In,
    Pipe,
    Dot,
    Append,
    Comma,
    Reference,
    LParen,
    RParen,
    LBracket,
    RBracket,
    LFlower,
    RFlower,
    Semicolon,
    Block,

    Import,
    Break,
    Continue,
    Return,
    If,
    Else,
    For,
    While,
    Operator,
    Let,
    Var,
    Mesh,
    Param,
    Anim,
    Play,
    Slide,
    Nil,
    Native,

    IntegerLiteral,
    FloatLiteral,
    // this means it looks most like a string literal
    // however it may actually be ilformed
    // the parser / compiler must actually verify the form
    StringLiteral,

    ArgumentLabel,
    Identifier,
}

impl Token {
    pub fn category(&self) -> TokenCategory {
        use Token::*;
        match self {
            Illegal => TokenCategory::Unknown,
            Newline | Whitespace => TokenCategory::Whitespace,
            StatefulReference | Plus | Minus | Multiply | Power | Divide | IntegerDivide
            | Assign | KeyValueMap | Eq | Ne | Lt | Le | Gt | Ge | And | Not | Or | In | Pipe
            | Comma | Dot | DotAssign | Append | Reference | Semicolon => TokenCategory::Operator,
            LParen | RParen | LBracket | RBracket | LFlower | RFlower => {
                TokenCategory::Punctutation
            }
            Block | Operator | Anim | Play | Break | Continue | Return | If | Else | For
            | While => TokenCategory::ControlFlow,
            Import | Let | Var | Mesh | Param | Slide | Nil | Native => {
                TokenCategory::NonControlFlowKeyword
            }
            IntegerLiteral | FloatLiteral => TokenCategory::NumericLiteral,
            StringLiteral => TokenCategory::TextLiteral,
            Comment => TokenCategory::Comment,
            Identifier => TokenCategory::Identifier,
            ArgumentLabel => TokenCategory::ArgumentLabel,
        }
    }

    pub fn description(&self) -> &'static str {
        match self {
            Token::Illegal => "<illegal>",
            Token::Newline => "<end of line>",
            Token::Whitespace => "<whitespace>",
            Token::Comment => "<comment>",
            Token::StatefulReference => "'$'",
            Token::Plus => "'+'",
            Token::Minus => "'-'",
            Token::Multiply => "'*'",
            Token::Power => "'^'",
            Token::Divide => "'/'",
            Token::IntegerDivide => "'//'",
            Token::KeyValueMap => "'->'",
            Token::Assign => "'='",
            Token::DotAssign => "'.='",
            Token::Eq => "'=='",
            Token::Ne => "'!='",
            Token::Lt => "'<'",
            Token::Le => "'<='",
            Token::Gt => "'>'",
            Token::Ge => "'>='",
            Token::And => "'and'",
            Token::Not => "'not'",
            Token::Or => "'or'",
            Token::In => "'in'",
            Token::Pipe => "'|'",
            Token::Dot => "'.'",
            Token::Append => "'..'",
            Token::Comma => "','",
            Token::Reference => "'&'",
            Token::LParen => "'('",
            Token::RParen => "')'",
            Token::LBracket => "'['",
            Token::RBracket => "']'",
            Token::LFlower => "'{'",
            Token::RFlower => "'}'",
            Token::Semicolon => "';'",
            Token::Block => "'block'",
            Token::Import => "'import'",
            Token::Break => "'break'",
            Token::Continue => "'continue'",
            Token::Return => "'return'",
            Token::If => "'if'",
            Token::Else => "'else'",
            Token::For => "'for'",
            Token::While => "'while'",
            Token::Operator => "'operator'",
            Token::Let => "'let'",
            Token::Var => "'var'",
            Token::Mesh => "'mesh'",
            Token::Param => "'param'",
            Token::Anim => "'anim'",
            Token::Play => "'play'",
            Token::Slide => "'slide'",
            Token::Nil => "'nil'",
            Token::Native => "'__monocurl__native__'",
            Token::IntegerLiteral => "<integer>",
            Token::FloatLiteral => "<float>",
            Token::StringLiteral => "<string>",
            Token::ArgumentLabel => "<argument label>",
            Token::Identifier => "<identifier>",
        }
    }

    pub fn autocomplete(&self) -> Option<&'static str> {
        match self {
            Token::Illegal => None,
            Token::Newline => None,
            Token::Whitespace => None,
            Token::Comment => None,
            Token::StatefulReference => Some("$"),
            Token::Plus => Some("+"),
            Token::Minus => Some("-"),
            Token::Multiply => Some("*"),
            Token::Power => Some("^"),
            Token::Divide => Some("/"),
            Token::IntegerDivide => Some("//"),
            Token::KeyValueMap => Some("->"),
            Token::Assign => Some("="),
            Token::DotAssign => Some(".="),
            Token::Eq => Some("=="),
            Token::Ne => Some("!="),
            Token::Lt => Some("<"),
            Token::Le => Some("<="),
            Token::Gt => Some(">"),
            Token::Ge => Some(">="),
            Token::And => Some("and"),
            Token::Not => Some("not"),
            Token::Or => Some("or"),
            Token::In => Some("in"),
            Token::Pipe => Some("|"),
            Token::Dot => Some("."),
            Token::Append => Some(".."),
            Token::Comma => Some(","),
            Token::Reference => Some("&"),
            Token::LParen => Some("("),
            Token::RParen => Some(")"),
            Token::LBracket => Some("["),
            Token::RBracket => Some("]"),
            Token::LFlower => Some("{"),
            Token::RFlower => Some("}"),
            Token::Semicolon => Some(";"),
            Token::Block => Some("block"),
            Token::Import => Some("import"),
            Token::Break => Some("break"),
            Token::Continue => Some("continue"),
            Token::Return => Some("return"),
            Token::If => Some("if"),
            Token::Else => Some("else"),
            Token::For => Some("for"),
            Token::While => Some("while"),
            Token::Operator => Some("operator"),
            Token::Let => Some("let"),
            Token::Var => Some("var"),
            Token::Mesh => Some("mesh"),
            Token::Param => Some("param"),
            Token::Anim => Some("anim"),
            Token::Play => Some("play"),
            Token::Slide => Some("slide"),
            Token::Nil => Some("nil"),
            Token::Native => None,
            Token::IntegerLiteral => None,
            Token::FloatLiteral => None,
            Token::StringLiteral => None,
            Token::ArgumentLabel => None,
            Token::Identifier => None,
        }
    }
}

#[derive(Default, Copy, Clone, Debug, PartialEq)]
pub enum TokenCategory {
    #[default]
    Unknown,
    Whitespace,
    Operator,
    // as in parentheses, brackets, ::, etc
    Punctutation,
    ControlFlow,
    NonControlFlowKeyword,
    ArgumentLabel,
    Identifier,
    NumericLiteral,
    TextLiteral,
    Comment,
}
