
// might need to add lambdas, labels
#[derive(Default, Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum Token {
    #[default]
    Illegal,

    Newline,
    Whitespace,

    Comment,

    StatefulReference,
    Plus,
    Minus,
    Multiply,
    Power,
    Divide,
    IntegerDivide,
    KeyValueMap,
    Assign,
    DotAssign,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    And,
    Not,
    Or,
    In,
    Pipe,
    Dot,
    Append,
    Comma,
    Reference,
    LParen,
    RParen,
    LBracket,
    RBracket,
    LFlower,
    RFlower,
    Semicolon,
    Block,

    Import,
    Break,
    Continue,
    Return,
    If,
    Else,
    For,
    While,
    Operator,
    Let,
    Var,
    Mesh,
    State,
    Param,
    Anim,
    Play,
    Slide,
    Native,

    IntegerLiteral,
    FloatLiteral,
    // this means it looks most like a string literal
    // however it may actually be ilformed
    // the parser / compiler must actually verify the form
    StringLiteral,

    ArgumentLabel,
    Identifier,
}

impl Token {
    pub fn category(&self) -> TokenCategory {
        use Token::*;
        match self {
            Illegal => TokenCategory::Unknown,
            Newline | Whitespace => TokenCategory::Whitespace,
            StatefulReference | Plus | Minus | Multiply | Power | Divide | IntegerDivide | Assign
            | KeyValueMap | Eq | Ne | Lt | Le | Gt | Ge | And | Not | Or | In
            | Pipe | Comma | Dot | DotAssign | Append | Reference | Semicolon => TokenCategory::Operator,
            LParen | RParen | LBracket | RBracket | LFlower | RFlower => TokenCategory::Punctutation,
            Block | Operator | Anim | Play | Break | Continue | Return | If | Else | For | While => TokenCategory::ControlFlow,
            Import | Let | Var | Mesh | State | Param | Slide | Native => {
                TokenCategory::NonControlFlowKeyword
            }
            IntegerLiteral | FloatLiteral => TokenCategory::NumericLiteral,
            StringLiteral => TokenCategory::TextLiteral,
            Comment => TokenCategory::Comment,
            Identifier => TokenCategory::Identifier,
            ArgumentLabel => TokenCategory::ArgumentLabel,
        }
    }

    pub fn description(&self) -> &'static str {
        match self {
            Token::Illegal => "<illegal>",
            Token::Newline => "<end of line>",
            Token::Whitespace => "<whitespace>",
            Token::Comment => "<comment>",
            Token::StatefulReference => "'$'",
            Token::Plus => "'+'",
            Token::Minus => "'-'",
            Token::Multiply => "'*'",
            Token::Power => "'^'",
            Token::Divide => "'/'",
            Token::IntegerDivide => "'//'",
            Token::KeyValueMap => "'->'",
            Token::Assign => "'='",
            Token::DotAssign => "'.='",
            Token::Eq => "'=='",
            Token::Ne => "'!='",
            Token::Lt => "'<'",
            Token::Le => "'<='",
            Token::Gt => "'>'",
            Token::Ge => "'>='",
            Token::And => "'and'",
            Token::Not => "'not'",
            Token::Or => "'or'",
            Token::In => "'in'",
            Token::Pipe => "'|'",
            Token::Dot => "'.'",
            Token::Append => "'..'",
            Token::Comma => "','",
            Token::Reference => "'&'",
            Token::LParen => "'('",
            Token::RParen => "')'",
            Token::LBracket => "'['",
            Token::RBracket => "']'",
            Token::LFlower => "'{'",
            Token::RFlower => "'}'",
            Token::Semicolon => "';'",
            Token::Block => "'block'",
            Token::Import => "'import'",
            Token::Break => "'break'",
            Token::Continue => "'continue'",
            Token::Return => "'return'",
            Token::If => "'if'",
            Token::Else => "'else'",
            Token::For => "'for'",
            Token::While => "'while'",
            Token::Operator => "'operator'",
            Token::Let => "'let'",
            Token::Var => "'var'",
            Token::Mesh => "'mesh'",
            Token::State => "'state'",
            Token::Param => "'param'",
            Token::Anim => "'anim'",
            Token::Play => "'play'",
            Token::Slide => "'slide'",
            Token::Native => "'__monocurl__native__'",
            Token::IntegerLiteral => "<integer>",
            Token::FloatLiteral => "<float>",
            Token::StringLiteral => "<string>",
            Token::ArgumentLabel => "<argument label>",
            Token::Identifier => "<identifier>",
        }
    }

    pub fn autocomplete(&self) -> &'static str {
        match self {
            Token::Illegal => "<illegal>",
            Token::Newline => "<end of line>",
            Token::Whitespace => "<whitespace>",
            Token::Comment => "<comment>",
            Token::StatefulReference => "$",
            Token::Plus => "+",
            Token::Minus => "-",
            Token::Multiply => "*",
            Token::Power => "^",
            Token::Divide => "/",
            Token::IntegerDivide => "//",
            Token::KeyValueMap => "->",
            Token::Assign => "=",
            Token::DotAssign => ".=",
            Token::Eq => "==",
            Token::Ne => "!=",
            Token::Lt => "<",
            Token::Le => "<=",
            Token::Gt => ">",
            Token::Ge => ">=",
            Token::And => "and",
            Token::Not => "not",
            Token::Or => "or",
            Token::In => "in",
            Token::Pipe => "|",
            Token::Dot => ".",
            Token::Append => "..",
            Token::Comma => ",",
            Token::Reference => "&",
            Token::LParen => "(",
            Token::RParen => ")",
            Token::LBracket => "[",
            Token::RBracket => "]",
            Token::LFlower => "{",
            Token::RFlower => "}",
            Token::Semicolon => ";",
            Token::Block => "block",
            Token::Import => "import",
            Token::Break => "break",
            Token::Continue => "continue",
            Token::Return => "return",
            Token::If => "if",
            Token::Else => "else",
            Token::For => "for",
            Token::While => "while",
            Token::Operator => "operator",
            Token::Let => "xlet",
            Token::Var => "var",
            Token::Mesh => "mesh",
            Token::State => "state",
            Token::Param => "param",
            Token::Anim => "anim",
            Token::Play => "play",
            Token::Slide => "slide",
            Token::Native => "__monocurl__native__",
            Token::IntegerLiteral => "<integer>",
            Token::FloatLiteral => "<float>",
            Token::StringLiteral => "<string>",
            Token::ArgumentLabel => "<argument label>",
            Token::Identifier => "<identifier>",
        }
    }
}

#[derive(Default, Copy, Clone, Debug, PartialEq)]
pub enum TokenCategory {
    #[default]
    Unknown,
    Whitespace,
    Operator,
    // as in parentheses, brackets, ::, etc
    Punctutation,
    ControlFlow,
    NonControlFlowKeyword,
    ArgumentLabel,
    Identifier,
    NumericLiteral,
    TextLiteral,
    Comment,
}
