use gpui::actions;

actions!(app, [Quit, OpenSettings, OpenKeyBindings, CheckForUpdates]);

actions!(
    document,
    [
        SaveActiveDocumentCustomPath,
        SaveActiveDocument,
        CloseActiveDocument,
        ExportImage,
        ExportVideo,
        ExportSlidesAsVideos
    ]
);

actions!(
    text_input,
    [
        Backspace,
        Delete,
        BackspaceWord,
        BackspaceLine,
        DeleteWord,
        DeleteLine,
        Enter,
        Tab,
        Untab,
        ToggleComment,
        ToggleSlideFold,
        Up,
        Left,
        Right,
        LeftWord,
        RightWord,
        Down,
        SelectLeft,
        SelectRight,
        SelectLeftWord,
        SelectRightWord,
        SelectUp,
        SelectDown,
        SelectHome,
        SelectEnd,
        SelectAll,
        Home,
        End,
        ShowCharacterPalette,
        Paste,
        Cut,
        Copy,
        OpenFind,
        CloseFind,
        FindNext,
        FindPrevious,
        ReplaceCurrent,
        ReplaceAll,
    ]
);

actions!(
    editor,
    [
        Undo,
        Redo,
        UnfocusEditor,
        ToggleHeadlessMode,
        TogglePresentationMode,
        ToggleParamsPanel,
        ToggleTimelineConsole,
        SyncViewportCamera,
        PlayOrShowPauseHint,
        TogglePlaying,
        SceneStart,
        SceneEnd,
        PrevSlide,
        NextSlide,
        EpsilonForward,
        EpsilonBackward,
        ZoomIn,
        ZoomOut,
    ]
);
